import { useNavigate } from "react-router-dom";

const T = { bg: "#0e1020", card: "#1a1e35", border: "#2a2f50", gold: "#ffc400", text: "#e8eaf6", muted: "#9ea3c0" };

const SECTIONS = [
  { title: "1. Acceptance of Terms", body: `By accessing or using The Legacy Circle, you agree to be bound by these Terms of Service and our Privacy Policy. If you are under 13, your parent or guardian must review and accept these Terms on your behalf before you may use the app.

If you do not agree to these Terms, do not use The Legacy Circle.` },

  { title: "2. Age Requirements & Parental Consent", body: `• Children under 13 may only use The Legacy Circle with verifiable parental consent per COPPA
• Parents/guardians consent on behalf of children under 13 by completing the parental verification process
• Users ages 13–17 may use the service independently; parents may still request access to account data
• Users must provide accurate age information — misrepresentation will result in immediate account termination
• Schools enrolling students must comply with FERPA and must notify parents before requiring use of this app
• We reserve the right to delete any account where consent requirements cannot be verified` },

  { title: "3. Acceptable Use Policy", body: `You agree NOT to:

• Share personal information (home address, phone number, school name, social media handles) with other users
• Bully, harass, threaten, demean, or exclude other learners
• Submit, share, or solicit sexual, violent, or otherwise inappropriate content
• Attempt to contact other learners outside the app
• Create accounts to circumvent bans, age requirements, or consent requirements
• Use the app for any purpose other than personal, non-commercial learning
• Reverse-engineer, scrape, copy, or distribute any app content, characters, or stories
• Upload malware or attempt to compromise platform security

Violation of this policy may result in immediate account termination and, where applicable, reporting to law enforcement and NCMEC.` },

  { title: "4. Glow Messages & Community Content", body: `The Glow Mentorship feature allows learners to send moderated encouragement to peers.

• All Glow Messages are reviewed before delivery
• Messages must be positive, age-appropriate, and under 120 characters
• No personal contact information may be shared in Glow Messages
• Harassing, sexual, or threatening Glows result in immediate account suspension
• Parents/guardians of both sender and recipient are notified of violations
• Story Feed posts must be educational, under 500 characters, and free of personal information
• We reserve the right to reject or remove any community content at our discretion` },

  { title: "5. Our Characters & Intellectual Property", body: `Justice, QJ, TJ, and Lyric are original characters owned by Legacy Circle LLC. All story content, character designs, dialogue, aura names, competency frameworks, and educational structure are protected by U.S. copyright law.

You may NOT:
• Reproduce or distribute our characters or stories commercially
• Create merchandise featuring our characters without written permission
• Create derivative works, fan fiction, or adaptations for commercial purposes

You MAY:
• Share screenshots of your personal learning progress on social media
• Reference The Legacy Circle for personal, educational, or journalistic purposes` },

  { title: "6. Indiana HB 1052 & Classroom Use", body: `The Legacy Circle is designed to align with Indiana HB 1052. Classroom use constitutes acknowledgment that:

• The educator/school is responsible for appropriate use per FERPA
• Student data may only be used for educational purposes
• The school will notify parents before requiring use of this app
• Teachers must not share student login credentials or profile data
• Schools must designate a FERPA-responsible administrator for student data requests` },

  { title: "7. AI Character Interactions", body: `The Legacy Circle features AI-powered character interactions.

• AI responses are generated by a secure, privacy-compliant language model
• No child's personal data is used to train AI models
• All AI content is reviewed for age-appropriateness before deployment
• Parents may request review or deletion of their child's AI interaction logs at any time
• AI characters will never ask for personal information, encourage inappropriate content, or simulate romantic relationships` },

  { title: "8. Screen Time & Parental Controls", body: `Parents may set daily screen time limits through the Guardian Vault. We do not guarantee that technical limitations will prevent all overuse. Parents remain responsible for supervising their children's device usage.

Recommended daily limits:
• Ages 2–4: 30 minutes
• Ages 5–7: 45 minutes
• Ages 8–10: 60 minutes
• Ages 11–14: 90 minutes` },

  { title: "9. Disclaimer of Warranties", body: `The Legacy Circle is provided "as is" and "as available." We make no warranties, express or implied, including:

• Warranties of merchantability or fitness for a particular purpose
• That the service will be uninterrupted, error-free, or free of viruses
• That all content meets individual state curricula standards outside Indiana

We strive for 99.9% uptime but cannot guarantee it.` },

  { title: "10. Limitation of Liability", body: `To the maximum extent permitted by applicable law, Legacy Circle LLC's total liability to any user shall not exceed the greater of: (a) the amount paid for premium services in the past 12 months, or (b) $100 USD.

We are not liable for: user-generated content, third-party services, specific learning outcomes, device compatibility issues, or data loss due to force majeure events (natural disasters, service outages, etc.).` },

  { title: "11. CSAM & Child Safety", body: `The Legacy Circle has zero tolerance for child sexual abuse material (CSAM) and any content that endangers minors.

• Any detected CSAM is immediately reported to NCMEC CyberTipline and cooperating law enforcement
• Accounts involved in sharing or soliciting CSAM are permanently terminated and reported
• We cooperate fully with law enforcement investigations involving child safety
• To report a child safety concern: ddortese@gmail.com or NCMEC at 1-800-843-5678` },

  { title: "12. Termination", body: `We may suspend or terminate accounts that:

• Violate these Terms of Service
• Pose a safety risk to other users
• Have unresolved COPPA consent issues
• Have been inactive for 12+ months (with 30 days' notice where possible)

Upon termination, all personal data is deleted within 30 days per our Privacy Policy. You may appeal terminations by emailing ddortese@gmail.com.` },

  { title: "13. Governing Law & Disputes", body: `These Terms are governed by the laws of the State of Indiana, USA, without regard to conflict of law principles.

Disputes shall be resolved in the courts of Marion County, Indiana, unless federal jurisdiction is required (e.g., COPPA enforcement by the FTC).

For COPPA-related disputes, the Federal Trade Commission has primary enforcement authority.` },

  { title: "14. Changes to These Terms", body: `We may update these Terms from time to time. When we do:

• We will update the "Last Updated" date at the top
• For significant changes, we will notify registered parents/guardians by email
• Continued use of The Legacy Circle after changes constitutes acceptance

If you disagree with any changes, you may delete your account at any time.` },

  { title: "15. Contact Us", body: `Legacy Circle LLC
Indianapolis, Indiana, USA
📧 ddortese@gmail.com
🌐 https://legacycircle.app

For COPPA compliance: ddortese@gmail.com
To report CSAM: NCMEC CyberTipline 1-800-843-5678 or missingkids.org
For FERPA questions: studentprivacy.ed.gov` },
];

export default function LCTermsOfService() {
  const navigate = useNavigate();

  return (
    <div style={{ fontFamily: "sans-serif", minHeight: "100vh", background: T.bg, color: T.text, paddingBottom: 60 }}>
      <div style={{ background: T.card, padding: "18px 20px", borderBottom: `1px solid ${T.border}`, position: "sticky", top: 0, zIndex: 10 }}>
        <div style={{ maxWidth: 720, margin: "0 auto", display: "flex", alignItems: "center", gap: 12 }}>
          <button onClick={() => navigate(-1)} style={{ background: "none", border: "none", color: T.gold, fontSize: 22, cursor: "pointer" }}>←</button>
          <div>
            <div style={{ fontSize: 17, fontWeight: 900 }}>Terms of Service</div>
            <div style={{ fontSize: 11, color: T.muted }}>The Legacy Circle · Effective April 2026</div>
          </div>
        </div>
      </div>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "24px 20px" }}>
        <div style={{ background: "#0e1020", borderRadius: 14, padding: "14px 18px", marginBottom: 28, border: `1px solid ${T.gold}30` }}>
          <div style={{ color: T.gold, fontWeight: 800, marginBottom: 4 }}>📚 The Legacy Circle — Learn. Grow. Glow.</div>
          <div style={{ color: T.muted, fontSize: 13, lineHeight: 1.5 }}>These Terms apply to all users of The Legacy Circle. COPPA · FERPA · GDPR-K · CCPA · Indiana HB 1052 compliant.</div>
        </div>

        {SECTIONS.map((s, i) => (
          <div key={i} style={{ marginBottom: 32 }}>
            <div style={{ fontSize: 15, fontWeight: 800, color: T.gold, marginBottom: 12, paddingBottom: 8, borderBottom: `1px solid ${T.border}` }}>
              {s.title}
            </div>
            <div style={{ color: T.muted, fontSize: 14, whiteSpace: "pre-line", lineHeight: 1.75 }}>
              {s.body}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
